# Generated by Django 4.1.3 on 2022-11-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='food', max_length=300),
        ),
    ]
